<a href="https://colab.research.google.com/github/malcolmrite-dsi/CPT-House-Predictions/blob/master/HousePriceModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the Libraries

In [1]:
import pandas as pd
import numpy as np

In [22]:

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error

from scipy import stats
import statsmodels.api as sm 

# Import Split Datasets

In [2]:
X_train_80 = np.genfromtxt('drive/My Drive/v1_X_train_80.csv',delimiter=',')
X_test_20 = np.genfromtxt("drive/My Drive/v1_X_test_20.csv",delimiter=',')
Y_train_80 = np.genfromtxt("drive/My Drive/v1_Y_train_80.csv",delimiter=',')
Y_test_20 = np.genfromtxt("drive/My Drive/v1_Y_test_20.csv",delimiter=',')


In [3]:
X_train_80

array([[  0.,   1.,   0., ...,   0.,   0.,  68.],
       [  0.,   1.,   0., ...,   0.,   0.,  56.],
       [  0.,   1.,   0., ...,   0.,   0.,  21.],
       ...,
       [  1.,   0.,   0., ...,   0.,   0.,  27.],
       [  0.,   0.,   1., ...,   1.,   0.,  16.],
       [  0.,   1.,   0., ...,   0.,   0., 100.]])

# Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_80 = sc.fit_transform(X_train_80)


In [17]:
X_train_80

array([[-0.42447636,  1.4061553 , -0.6096948 , ..., -0.9228164 ,
        -0.2093435 ,  0.52404391],
       [-0.42447636,  1.4061553 , -0.6096948 , ..., -0.9228164 ,
        -0.2093435 ,  0.12414244],
       [-0.42447636,  1.4061553 , -0.6096948 , ..., -0.9228164 ,
        -0.2093435 , -1.04223684],
       ...,
       [ 2.3558438 , -0.711159  , -0.6096948 , ..., -0.9228164 ,
        -0.2093435 , -0.8422861 ],
       [-0.42447636, -0.711159  ,  1.64016488, ...,  1.08363917,
        -0.2093435 , -1.20886245],
       [-0.42447636,  1.4061553 , -0.6096948 , ..., -0.9228164 ,
        -0.2093435 ,  1.59044782]])

In [5]:
X_test_20 = sc.fit_transform(X_test_20)

# Modelling

In [23]:
reg = RandomForestRegressor(n_estimators = 200, random_state = 1)
    # Fit Model
reg.fit(X_train_80, Y_train_80)


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=1, verbose=0, warm_start=False)

In [24]:
y_pred = reg.predict(X_test_20)
val_mae = mean_absolute_error(y_pred, Y_test_20)
print("Validation MAE when not specifying max_leaf_nodes: {:,.0f}".format(val_mae))

Validation MAE when not specifying max_leaf_nodes: 3,189,608


In [25]:
y_pred

array([ 2961575.        ,  1451364.17640693,  1528647.40079365,
        2222578.00515627,  7157707.51984127,  2336718.94612117,
        9437442.23214286,  1100121.97079365,  3616041.01309524,
        2901129.11061161,  2880165.47619048,  1404964.58333333,
        5912904.83333333,  2329213.38633589,  5684443.48214286,
        7805823.5701656 , 11495797.54884005,  3088763.92857143,
        3078718.35714286,  2513925.        ,  2887827.38005051,
        2051546.70238095,  1759552.08333333, 12393593.79093129,
        2329213.38633589,  2201326.51256796,  2329213.38633589,
        7157707.51984127,  2207223.33333333,  4584458.0731907 ,
        1363867.6084885 ,  2880165.47619048,  8044281.34920635,
        1907604.78998779,  1208638.89568765, 12736287.48681874,
        4860997.14285714, 10800332.68127706,  1404964.58333333,
        5656241.73014486,  3173760.5       ,  2397500.41666667,
        1451364.17640693,  1436833.39285714,  2201326.51256796,
        2681357.51190476,  9047982.61904